browser=chrome
url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
implicitWait=30
explicitWait=30
# Retry configuration
retry.count=2

seleniumGrid=true

#Test au niveau container docker
gridURL=http://selenium-hub:4444gridURL=http://selenium-hub:4444

#Test au niveau local
#gridURL=http://localhost:4444
